""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"
" Vim main config
" by Sergey Yakovlev (me@klay.me)
" https://github.com/sergeyklay/
"
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

runtime startup/bundles.vim
runtime startup/settings.vim
runtime startup/console.vim

set history=1000               " cmdline history table size
set nowrap                     " don't wrap visible lines
set wildmenu                   " enhanced cmdline completion
set wildchar=<Tab>             " type tab in cmdline to start wildcard expansion
set wildmode=longest:full,full " cmdline completion mode settings
set makeprg=make               " application for build - make
set whichwrap=<,>,[,],h,l      " allow line-wrapped navigation
set fencs=utf8,cp1251,koi8r,cp866 " possible encodings of files
set showmode                   " show whether in insert, visual mode etc
set noacd                      " current directory - where is the active file
set tpm=100                    " maximum number of tab pages to be opened
set ex                         " use .vimrc from current dir
set list                       " display the tabs, and leading spaces
set lcs=tab:»\ ,trail:·,eol:¶  " how to display non-printing characters
                               " where sensible
set tw=80                      " maximum column width of inserted text
                               " longer lines are broken after whitespace
set cc=+1                      " highlight border for tw
set nohidden                   " when closing tab, remove the buffer
set shell=/bin/bash            " set the shell to be used
set formatoptions=qrn1         " correctly handle long lines
set cursorline                 " display cursor line
set scrolloff=3                " minimal number of screen to keep above
                               " and below the cursor

" save on loss of focus
au FocusLost * :wa

" more complete information when pressing <C-g>
map <C-g> g<C-g>
" save sesson to file
map <C-k> :mks! ~/.vim/session/sess.vim<CR>
" restore sesion from file
map <C-l> :so ~/.vim/session/sess.vim<CR>
" Map a specific shortcut to open NERDTree
map <C-n> :NERDTreeToggle<CR>
" that will list file names in the current directory
map <F2> :e <C-d>

" ; the same as :
nnoremap ; :

" autocommand stuff

" only do this part when compiled with support for autocommands
if has("autocmd")
  " put these in an autocmd group, so that we can delete them easily
  augroup vimrcEx
    au!

    " open a NERDTree automatically
    " when vim starts up if no files were specified
    autocmd vimenter * if !argc() | NERDTree | endif

    " for all text files set 'textwidth' to 78 characters
    autocmd FileType text setlocal textwidth=78
    " for all C files set 'textwidth' to 78 characters.
    autocmd bufreadpre *.c setlocal textwidth=78
    " some settings for php
    autocmd FileType php  setlocal makeprg=zca\ %<.php
    autocmd FileType php  setlocal errorformat=%f(line\ %l):\ %m

    " when editing a file, always jump to the last known cursor position
    " don't do it when the position is invalid or when inside an event handler
    autocmd BufReadPost *
      \ if line("'\"") > 1 && line("'\"") <= line("$") |
      \   exe "normal! g`\"" |
      \ endif
  augroup END
else

endif

if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
        \ | wincmd p | diffthis
endif

" using templates for new files.
" in order for plugin was able to find a specific template,
" files must be named template.*, and should be located in
" ~/.vim/template directory
augroup template-plugin
  autocmd User plugin-template-loaded call s:template_keywords()
augroup END

function! s:template_keywords()
  " file name
  if search('<+FILE_NAME+>')
    silent %s/<+FILE_NAME+>/\=toupper(expand('%:t:r'))/g
  endif
  " cursor position
  if search('<+CURSOR+>')
    execute 'normal! "_da>'
  endif
  " current date
  silent %s/<+DATE+>/\=strftime('%Y-%m-%d')/g
endfunction
