#!/usr/bin/env zsh

# function venv-init {

[ -z "$VIRTUAL_ENV" ] && {
  [ -f "$HOME/.venv/local/bin/activate" ] && {
    source "$HOME/.venv/local/bin/activate"
  }
}

# }

# Local Variables:
# mode: sh
# End:
