#!/usr/bin/env zsh

# function zcompdf {

pushd -q $ZDOT_DEFUNS

for defun in * ; do
  if [ ${defun%.zwc} = ${defun} ] ; then
    # Do compilation if:
    #
    # - ``function'' file is exists and it is not empty
    # - ``function.zwc`` is absent OR ``function'' is newer
    #   than ``function.zwc''
    if [[ -s $defun && (! -s ${defun}.zwc || $defun -nt ${defun}.zwc) ]]
    then
      [ -f ${defun}.zwc ] && rm -f ${defun}.zwc
      zcompile $defun
    fi
  fi
done

popd -q

# }

# Local Variables:
# mode: sh
# End:
