# Linux-wide Zsh environment configuration.
#
# This file is sourced on all invokations of zsh.
#   .zshenv -> [zshenv] -> .zprofile -> .zshrc -> .zlogin
#                ^
#   -------------

# OS specific aliases.
[ -r $ZSHDDIR/conf.d/OS/$OSSHORT/xdg-dirs ] && {
  source $ZSHDDIR/conf.d/OS/$OSSHORT/xdg-dirs
}

# Local Variables:
# mode: sh
# End:
