# Linux-wide Zsh startup file.
#
# This file is sourced on all interactive shells.
#   .zshenv -> .zprofile -> .zshrc -> [zhrc] .zlogin
#                                       ^
#   ------------------------------------
#
# Used for setting user's interactive shell configuration and
# executing commands for Linux, will be read when starting as an
# interactive shell.

# https://gnunn1.github.io/tilix-web/manual/vteconfig
if [ $TILIX_ID ] || [ $VTE_VERSION ]
then
  if [ -f /etc/profile.d/vte-2.91.sh ]
  then
    source /etc/profile.d/vte-2.91.sh
  elif [ -f /etc/profile.d/vte.sh ]
  then
    source /etc/profile.d/vte.sh
  fi
fi

# Local Variables:
# mode: sh
# End:
