# macOS-wide Zsh environment configuration.
#
# This file is sourced on all invokations of zsh.
#   .zshenv -> [zshenv] -> .zprofile -> .zshrc -> .zlogin
#                ^
#   -------------

# See: https://stackoverflow.com/q/7165108/1661465
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Local Variables:
# mode: sh
# End:
