# macOS-wide Zsh environment configuration.
#
# This file is sourced on all invocations of the shell, unless the
# `-f' option is set.
#   .zshenv -> [zshenv] -> .zprofile -> .zshrc -> .zlogin

# See: https://stackoverflow.com/q/7165108/1661465
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
export LC_ALL LANG
