# macOS-wide Zsh startup file.
#
# This file is sourced on all interactive shells.
#   .zshenv -> .zprofile -> .zshrc -> [zhrc] -> .zlogin
#                                       ^
#   ------------------------------------
#
# Used for setting user's interactive shell configuration and
# executing commands for macOS, will be read when starting as an
# interactive shell.

[ -d /usr/local/share/zsh/site-functions ] &&
  fpath=("/usr/local/share/zsh/site-functions" $fpath)

# Local Variables:
# mode: sh
# End:
