#!/usr/bin/env zsh
#
# Copyright (c) 2020-2022, Serghei Iakovlev
#
# A shell function to clean zsh cache and temporary files.

[ -z $ZSHCACHEDIR ] && return 0
[ ! -d $ZSHCACHEDIR ] && return 0

# Do not query the user before executing 'rm *' or 'rm path/*'.
setopt rm_star_silent

# Environment files.
rm -f $ZSHCACHEDIR/env/*

# Lock file for compiled functions.
rm -f $ZSHCACHEDIR/zwcs

[ -d $ZDOTDIR/.config/zsh/lib/functions ] && {
  # Compiled functions.
  rm -f $ZDOTDIR/.config/zsh/lib/functions/*.zwc
}

# Enable option back.
setopt no_rm_star_silent
